### ISSUE TITLE
java.lang.ClassCastException: com.github.plokhotnyuk.rtree2d.core.RTreeNode cannot be cast to com.github.plokhotnyuk.rtree2d.core.RTreeEntry

### ISSUE THREAD

**Issue by JonasAckermann** [plokhotnyuk/rtree2d#176]
Hi!

Not sure if this is a good place to ask, but I am kind of stuck.

We've been using rtree2d without any issues for roughly 1.5 years. 
Suddenly, this error keeps appearing randomly when using `.nearestK()`:

```scala 
java.lang.ClassCastException: com.github.plokhotnyuk.rtree2d.core.RTreeNode cannot be cast to com.github.plokhotnyuk.rtree2d.core.RTreeEntry
	at com.github.plokhotnyuk.rtree2d.core.RTreeNode.nearest(RTree.scala:364)
	at com.github.plokhotnyuk.rtree2d.core.RTreeNode.nearest(RTree.scala:378)
	at com.github.plokhotnyuk.rtree2d.core.RTreeNode.nearest(RTree.scala:378)
	at com.github.plokhotnyuk.rtree2d.core.RTree$$anon$3.<init>(RTree.scala:204)
	at com.github.plokhotnyuk.rtree2d.core.RTree.nearestK(RTree.scala:203)
	at com.github.plokhotnyuk.rtree2d.core.RTree.nearestK$(RTree.scala:200)
	at com.github.plokhotnyuk.rtree2d.core.RTreeNode.nearestK(RTree.scala:353)
       [...omitted...]
	at akka.actor.typed.internal.BehaviorImpl$ReceiveMessageBehavior.receive(BehaviorImpl.scala:150)
	at akka.actor.typed.Behavior$.interpret(Behavior.scala:274)
	at akka.actor.typed.Behavior$.interpretMessage(Behavior.scala:230)
	at akka.actor.typed.internal.adapter.ActorAdapter.handleMessage(ActorAdapter.scala:126)
	at akka.actor.typed.internal.adapter.ActorAdapter.aroundReceive(ActorAdapter.scala:106)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:573)
	at akka.actor.ActorCell.invoke(ActorCell.scala:543)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:269)
	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

Sadly, I've not been able to reproduce it locally, or even by querying our service for locations which seemingly led to the crash.

The tree should contain less than 20k entries. This number has not increased significantly in the past few months.
The tree is constructed with the default capacity.
`k` is set to 10, `maxDist` varies in the 3000m range.

rtree2d version: 0.9.0 (can't spot any code changes in that area)
Scala version: 2.13.2
Java version: 8 (Amazon Coretto)

Has this been encountered before?
Any pointers towards how we could mitigate this would be much appreciated!

**Comment by plokhotnyuk** [comment]
@JonasAckermann Hi, Jonas! Thanks for reporting!

I have reproduced the same runtime exception after using a different `RTree` generator.

**Comment by JonasAckermann** [comment]
Thank you so much!
