### ISSUE TITLE
NoSuchMethod error creating entries in Scala 2.11.12 / Spark 2.4.3

### ISSUE THREAD

**Issue by arjology** [plokhotnyuk/rtree2d#59]
Hi, when trying the examples in the readme I run into this following error. 
I have downloaded the jar to my local maven repo.
- Spark 2.4.3
- Scala 2.11.12 

```
scala> import com.sizmek.rtree2d.core._
import com.sizmek.rtree2d.core._

scala> import SphericalEarth._
import SphericalEarth._

scala> val city1 = entry(50.0614f, 19.9383f, "Krakow")
java.lang.NoSuchMethodError: scala.Product.$init$(Lscala/Product;)V
  at com.sizmek.rtree2d.core.RTreeEntry.<init>(RTree.scala:332)
  at com.sizmek.rtree2d.core.Spherical.entry(Geometry.scala:107)
  at com.sizmek.rtree2d.core.Spherical.entry$(Geometry.scala:102)
  at com.sizmek.rtree2d.core.SphericalEarth$.entry(Geometry.scala:230)
  ... 53 elided
```

**Comment by plokhotnyuk** [comment]
@arjology please ensure that both Scala version and version of downloaded jar are matching.

Here is how it works in Scala REPL:
```
andriy@notebook:~$ /opt/scala-2.11.12/bin/scala
Welcome to Scala 2.11.12 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_212).
Type in expressions for evaluation. Or try :help.

scala> :require /home/andriy/Downloads/rtree2d-core_2.11-0.8.0.jar
Added '/home/andriy/Downloads/rtree2d-core_2.11-0.8.0.jar' to classpath.

scala> import com.sizmek.rtree2d.core._
import com.sizmek.rtree2d.core._

scala> import SphericalEarth._
import SphericalEarth._

scala> val city1 = entry(50.0614f, 19.9383f, "Krakow")
city1: com.sizmek.rtree2d.core.RTreeEntry[String] =
RTreeEntry(50.0614,19.9383,50.0614,19.9383,Krakow)
```

If you still have an error please provide exact steps to reproduce.

**Comment by arjology** [comment]
oh my goodness that was so simply  ! thanks :)
